name = "netstring"
version = "1.0.0"
description = "Gleam library for encoding and decoding Netstrings."
licences = ["MIT"]
repository = { type = "github", user = "jtdowney", repo = "netstring" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
unitest = ">= 1.4.2 and < 2.0.0"
